### ISSUE TITLE
Comments provides wrong Information

### ISSUE THREAD

**Issue by savinnpm** [neptune-mutual-blue/protocol#112]
The comment and the code in the following file say two different things.

filename; `ProtoUtilV1.sol`
![image](https://user-images.githubusercontent.com/95403423/181224274-47019199-6a3c-4862-b52e-138057ed2907.png)

The comment should be `Reverts if the caller is not one of the protocol member`

**Comment by binodnpm** [comment]
Closed for the time being; solutions have already been included in #133. Please reopen PR #133 after the audit has been completed. We will then review it.
