### ISSUE TITLE
Missing params on function documentation [libraries]

### ISSUE THREAD

**Issue by savinnpm** [neptune-mutual-blue/protocol#114]
- Some parameters are missing from the present documentation in one or more files under `contracts/libraries`

eg:  A function in `ProtoUtilV1.sol` has missing params `s` and `key` on documentation
![image](https://user-images.githubusercontent.com/95403423/181399070-0168f95a-b469-46ef-9c16-fd08a06cff27.png)

**Comment by binodnpm** [comment]
Closed for the time being; solutions have already been included in #133. Please reopen PR #133 after the audit has been completed. We will then review it.
