### ISSUE TITLE
Missing params documentation under `contracts` 

### ISSUE THREAD

**Issue by savinnpm** [neptune-mutual-blue/protocol#118]
- Similar to [Issue #114](https://github.com/neptune-mutual-blue/protocol/issues/114)
- Some parameters are missing from the present documentation in one or more files under `contracts/core`, `contracts/interfaces`, `contracts/pool`

**Comment by binodnpm** [comment]
Closed for the time being; solutions have already been included in #133. Please reopen PR #133 after the audit has been completed. We will then review it.
