### ISSUE TITLE
Update function documentations

### ISSUE THREAD

**Issue by al-neptune** [neptune-mutual-blue/protocol#120]
Below are the example of outdated and mistakes in the documentations

![Screen Shot 2022-08-01 at 12 59 33 PM](https://user-images.githubusercontent.com/104489911/182075558-5ccfd2b2-ae1f-404c-8e72-d51bd5bed21f.png)
- The parameter `amount` is not included in the function documentation

---------------

![Screen Shot 2022-08-01 at 12 58 11 PM](https://user-images.githubusercontent.com/104489911/182075693-68b40a63-e8f4-49dd-baf7-cbab3a7dda43.png)
- The parameter `coverKey` is duplicated

**Comment by binodnpm** [comment]
Closed for the time being; solutions have already been included in #133. Please reopen PR #133 after the audit has been completed. We will then review it.
