### ISSUE TITLE
Missing documentation for the product status

### ISSUE THREAD

**Issue by flashburst** [neptune-mutual-blue/protocol#126]
The product status which is being used in `addProduct`, `updateProduct` and `isActiveProductInternal` functions is not documented properly anywhere except in comments of `addProductInternal` function

https://github.com/neptune-mutual-blue/protocol/blob/a98fcce3657d80814f2aca67a4a8a3534ff8da2d/contracts/libraries/CoverLibV1.sol#L200-L205

However, the name **product status** is confusing as it's already used to specify the resolution status of a product in the protocol

https://github.com/neptune-mutual-blue/protocol/blob/a98fcce3657d80814f2aca67a4a8a3534ff8da2d/contracts/libraries/CoverUtilV1.sol#L23-L31

## addProduct
The first item of the last argument of `addProduct` function is documented as **product status** - `values[0]`. This parameter can be omitted as there is only one value accepted to execute the transaction successfully.

```solidity
require(values[0] == 1, "Status must be active");
```

## Question
Is there any need of having two different statuses for "Retired" and "Deleted" ? As they both offer almost same functionality as of now.

**Comment by binodnpm** [comment]
Closed for the time being; solutions have already been included in #133. Please reopen PR #133 after the audit has been completed. We will then review it.
