### ISSUE TITLE
[OZ] L-08 No unstaking window

### ISSUE THREAD

**Issue by binodnpm** [neptune-mutual-blue/protocol#151]
**Please note that [OpenZeppelin](https://www.openzeppelin.com/) reported this issue.**

> After an incident is resolved, successful stakers can retrieve their rewards [provided the incident has not been finalized](https://github.com/neptune-mutual-blue/protocol/blob/73fc82fbe0d1388867b7df669983fe42760daeb1/contracts/libraries/ValidationLibV1.sol#L425). When the incident occurred, they will have [at least the claim period](https://github.com/neptune-mutual-blue/protocol/blob/73fc82fbe0d1388867b7df669983fe42760daeb1/contracts/core/governance/resolution/Finalization.sol#L60). However, if the incident was successfully disputed, there is no claim period and the incident can be finalized immediately before stakers have been provided sufficient time to claim their rewards. Consider including an unstaking window for this scenario.

**Comment by rudolfnep** [comment]
For incidents resolved as `false reporting`, we intend to restore the cover status to operational as soon as possible. This flexibility allows us to accomplish a speedier finalization while still allowing the tokenholder community sufficient time to unstake their claim (with reward) on a case-by-case basis.
