### ISSUE TITLE
[OZ] N-07 Duplicate token supply tracking

### ISSUE THREAD

**Issue by binodnpm** [neptune-mutual-blue/protocol#177]
**Please note that [OpenZeppelin](https://www.openzeppelin.com/) reported this issue.**

> The NPM token tracks [the number of tokens that have been issued](https://github.com/neptune-mutual-blue/protocol/blob/73fc82fbe0d1388867b7df669983fe42760daeb1/contracts/core/token/NPM.sol#L11). This should be identical to the [total supply](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.4/contracts/token/ERC20/ERC20.sol#L40) if the tokens are never burned. It's worth noting that the code base [transfers funds to a burner address](https://github.com/neptune-mutual-blue/protocol/blob/73fc82fbe0d1388867b7df669983fe42760daeb1/contracts/core/governance/resolution/Unstakable.sol#L108) instead of reducing the supply.
>
> Consider disabling the `burn` functionality so that the total issued amount does not need to be tracked and updated separately.

**Comment by rudolfnep** [comment]
Given that the NPM token and protocol will be deployed on different blockchains, this is the proper approach. Ethereum is the only chain where `token burn` occurs. The burned tokens are transferred to a specified address on each chain and then bridged back to Ethereum on a regular basis.
